#!/usr/bin/ruby
# This is an interactive Ruby shell for wmii.
# - Press the TAB key for command completion.

=begin
  Copyright 2006 Suraj N. Kurapati

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
=end

require 'irb'
require 'irb/completion'

module IRB
  # Starts IRB within the context of the given object.
  # This code was taken from: http://www.therubymine.com/articles/2007/01/29/programmare-dallinterno
  def IRB.start_session aContextObj
    setup(nil)
    irb = IRB::Irb.new(WorkSpace.new(aContextObj))
    @CONF[:MAIN_CONTEXT] = irb.context
    catch(:IRB_EXIT) { irb.eval_input }
  end
end

if __FILE__ == $0
  # show usage info
    require 'rdoc/usage'
    RDoc::usage_no_exit

  # start the IRB session
    $:.unshift File.dirname(__FILE__)
    require 'rc'

    IRB.start_session Wmii
end
