#!/usr/bin/ruby
#
# This is an interactive Ruby shell for wmii.
# - Press the TAB key for command completion.

#--
# Copyright 2006-2007 Suraj N. Kurapati
# See the file named LICENSE for details.

require 'irb'
require 'irb/completion'

module IRB
  # Starts IRB within the context of the given object.
  #--
  # Adapted from Massimiliano Mirra:
  # <http://www.therubymine.com/articles/2007/01/29/programmare-dallinterno>
  def IRB.start_session aContextObj
    setup(nil)
    irb = IRB::Irb.new(WorkSpace.new(aContextObj))
    @CONF[:MAIN_CONTEXT] = irb.context
    catch(:IRB_EXIT) { irb.eval_input }
  end
end

if __FILE__ == $0
  # show usage info
    require 'rdoc/usage'
    RDoc::usage_no_exit

  # start the IRB session
    $: << File.dirname(__FILE__)
    require 'wm'

    IRB.start_session Wmii
end
